networks:
  mgmt:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-3
    ipam:
      config:
      - subnet: 172.3.0.0/24
  r1-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-4
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r1-gi0
  r1-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-5
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r1-gi1
  r1-gi2-r2-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-0
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r1-gi2-r2-gi1
  r1-gi3-r3-gi1:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-1
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r1-gi3-r3-gi1
  r1-gi4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-6
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r1-gi4
  r1-gi5:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-7
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r1-gi5
  r2-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-8
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r2-gi0
  r2-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-9
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r2-gi2
  r2-gi3-r3-gi2:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-2
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r2-gi3-r3-gi2
  r2-gi4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-10
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r2-gi4
  r2-gi5:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-11
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r2-gi5
  r3-gi0:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-12
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r3-gi0
  r3-gi3:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-13
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r3-gi3
  r3-gi4:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-14
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r3-gi4
  r3-gi5:
    driver_opts:
      com.docker.network.container_iface_prefix: xr-15
      com.docker.network.driver.mtu: 9000
    internal: true
    name: r3-gi5
services:
  r1:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: r1
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-40,xr_name=Gi0/0/0/0;linux:xr-50,xr_name=Gi0/0/0/1;linux:xr-00,xr_name=Gi0/0/0/2;linux:xr-10,xr_name=Gi0/0/0/3;linux:xr-60,xr_name=Gi0/0/0/4;linux:xr-70,xr_name=Gi0/0/0/5
      XR_MGMT_INTERFACES: linux:xr-30,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.11.2
    networks:
      mgmt:
        ipv4_address: 172.3.0.101
      r1-gi0: null
      r1-gi1: null
      r1-gi2-r2-gi1: null
      r1-gi3-r3-gi1: null
      r1-gi4: null
      r1-gi5: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./r1.xr_startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - r1:/xr-storage/
  r2:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: r2
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-80,xr_name=Gi0/0/0/0;linux:xr-00,xr_name=Gi0/0/0/1;linux:xr-90,xr_name=Gi0/0/0/2;linux:xr-20,xr_name=Gi0/0/0/3;linux:xr-100,xr_name=Gi0/0/0/4;linux:xr-110,xr_name=Gi0/0/0/5
      XR_MGMT_INTERFACES: linux:xr-30,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.11.2
    networks:
      mgmt:
        ipv4_address: 172.3.0.102
      r1-gi2-r2-gi1: null
      r2-gi0: null
      r2-gi2: null
      r2-gi3-r3-gi2: null
      r2-gi4: null
      r2-gi5: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./r2.xr_startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - r2:/xr-storage/
  r3:
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FSETID
    - FOWNER
    - MKNOD
    - NET_RAW
    - SETGID
    - SETUID
    - SETFCAP
    - SETPCAP
    - NET_BIND_SERVICE
    - SYS_CHROOT
    - KILL
    - AUDIT_WRITE
    - SYS_NICE
    - SYS_ADMIN
    - SYS_RESOURCE
    - NET_ADMIN
    - SYS_PTRACE
    - IPC_LOCK
    cap_drop:
    - all
    container_name: r3
    devices:
    - /dev/fuse
    - /dev/net/tun
    environment:
      XR_EVERY_BOOT_CONFIG: /etc/xrd/startup.cfg
      XR_INTERFACES: linux:xr-120,xr_name=Gi0/0/0/0;linux:xr-10,xr_name=Gi0/0/0/1;linux:xr-20,xr_name=Gi0/0/0/2;linux:xr-130,xr_name=Gi0/0/0/3;linux:xr-140,xr_name=Gi0/0/0/4;linux:xr-150,xr_name=Gi0/0/0/5
      XR_MGMT_INTERFACES: linux:xr-30,xr_name=Mg0/RP0/CPU0/0,chksum
    image: ios-xr/xrd-control-plane:7.11.2
    networks:
      mgmt:
        ipv4_address: 172.3.0.103
      r1-gi3-r3-gi1: null
      r2-gi3-r3-gi2: null
      r3-gi0: null
      r3-gi3: null
      r3-gi4: null
      r3-gi5: null
    pids_limit: -1
    security_opt:
    - apparmor=unconfined
    - label=disable
    stdin_open: true
    tty: true
    volumes:
    - source: ./r3.xr_startup.cfg
      target: /etc/xrd/startup.cfg
      type: bind
    - r3:/xr-storage/
version: '2.4'
volumes:
  r1:
    name: r1
  r2:
    name: r2
  r3:
    name: r3
